const menuList = [
    {
        title:'首页',
        key:'/home'
    },{
        title:'UI',
        key:'/ui',
        children:[
            {
                title:'按钮',
                key:'/ui/button',
            },{
                title:'弹框',
                key:'/ui/modals',
            },
            {
                title:'Loading',
                key:'/ui/loading',
            },
            {
                title:'通知提醒',
                key:'/ui/notification',
            },
            {
                title:'全局Message',
                key:'/ui/message',
            },
            {
                title:'Tab页签',
                key:'/ui/tabs',
            },{
                title:'图标画廊',
                key:'/ui/gallery',
            },{
                title:'轮播图',
                key:'/ui/carousel',
            }
        ]
    },{
        title:'表单',
        key:'/form',
        children:[
            {
                title:'登录表单',
                key:'/form/login',
            },
            {
                title:'注册表单',
                key:'/form/reg',
            }
        ]
    },{
        title:'表格',
        key:'/table',
        children:[
            {
                title:'基础表格',
                key:'/table/basicTable'
            },
            {
                title:'进阶表格',
                key:'/table/advancedTable'
            }
        ]
    },{
        title:'富文本',
        key:'404'
    },{
        title:'城市管理',
        key:'/city'
    },{
        title:'订单管理',
        key:'/order'
    },{
        title:'员工管理',
        key:'/user'
    },{
        title:'车辆地图',
        key:'/bikemap'
    },{
        title:'图表',
        key:'/charts/',
        children:[
            {
                title:'柱状图',
                key:'/charts/bar'
            },{
                title:'饼状图',
                key:'/charts/pie' 
            },{
                title:'折线图表',
                key:'/charts/line'
            }
        ]
    },{
        title:'权限设置',
        key:'/permission'
    },
];
export default menuList;